config/routes.rb
Info2310::Application.routes.draw do
  resources :micro_posts

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  root to: 'static_pages#home'

end

app/models/micro_post.rb
class MicroPost < ActiveRecord::Base
  attr_accessible :content, :user_id
  validates :user_id, presence: true
  validates :content, presence: true,
    length: { minimum: 5, maximum: 140 }
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :name, :password

  validates :password, presence: true, if: "hashed_password.blank?"
  
  validates :name, presence: true,
                      length: { minimum: 4, maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                        format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
  has_many :micro_posts

  before_save :encrypt_password

  def encrypt_password
    self.salt ||= Digest::SHA256.hexdigest("--#{Time.now.to_s}- -#{email}--")
    self.hashed_password = encrypt(password)
  end

  def encrypt(raw_password)
    Digest::SHA256.hexdigest("--#{salt}--#{raw_password}--")
  end

  def self.authenticate(email, plain_text_password)
    user = self.find_by_email(email)
    if (user == nil)
      return nil
    end
    if (user.hashed_password == user.encrypt(plain_text_password))
      return user
    else
      return nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionHelper
end

app/controllers/micro_posts_controller.rb
class MicroPostsController < ApplicationController
  # GET /micro_posts
  # GET /micro_posts.json
  def index
    @micro_posts = MicroPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @micro_posts }
    end
  end

  # GET /micro_posts/1
  # GET /micro_posts/1.json
  def show
    @micro_post = MicroPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micro_post }
    end
  end

  # GET /micro_posts/new
  # GET /micro_posts/new.json
  def new
    @micro_post = MicroPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micro_post }
    end
  end

  # GET /micro_posts/1/edit
  def edit
    @micro_post = MicroPost.find(params[:id])
  end

  # POST /micro_posts
  # POST /micro_posts.json
  def create
    @micro_post = MicroPost.new(params[:micro_post])

    respond_to do |format|
      if @micro_post.save
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully created.' }
        format.json { render json: @micro_post, status: :created, location: @micro_post }
      else
        format.html { render action: "new" }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /micro_posts/1
  # PUT /micro_posts/1.json
  def update
    @micro_post = MicroPost.find(params[:id])

    respond_to do |format|
      if @micro_post.update_attributes(params[:micro_post])
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micro_posts/1
  # DELETE /micro_posts/1.json
  def destroy
    @micro_post = MicroPost.find(params[:id])
    @micro_post.destroy

    respond_to do |format|
      format.html { redirect_to micro_posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if (user == nil)
        flash[:error] = "Invalid email/password combination"
        redirect_to new_session_path
    else
        flash[:notice] = "Welcome, #{user.email}!"
        sign_in(user)
        redirect_to user_path(user)
    end
  end

  def destroy
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
    def full_title(page_title)
        base_title = "INFO2310 Microposter"
        if page_title.empty?
            base_title
        else
            "#{base_title} | #{page_title}"
        end
    end
end

app/helpers/session_helper.rb
module SessionHelper
  
  def sign_in(user)
    cookies[:current_user_id] = user.id
    self.current_user = user
  end

  def sign_out_user
    cookies.delete :current_user_id
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_id(cookies[:current_user_id])
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <small>
        <%= link_to 'Rails Tutorial', 'http://railstutorial.org/' %>
        by Michael Hartl
    </small>
    |
    <%= link_to "INFO2310", 'http://curails.herokuapp.com' %>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">

            <%= link_to "MicroPoster", root_path, class: 'brand' %>

            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><%= link_to 'Home', root_path %></li>
                    <li><%= link_to 'Help', static_pages_help_path %></li>
                    <li><%= link_to 'About', static_pages_about_path %></li>
                    <% if signed_in? %>
                        <li><%= link_to 'My Profile', user_path(current_user) %></li>
                        <li><%= link_to 'My Account', edit_user_path(current_user) %></li>
                        <li><%= link_to 'Logout', session_path(current_user), method: :delete %></li>
                    <% else %>
                        <li><%= link_to 'Login', new_session_path %></li>
                    <% end %>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container"> 

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %> 

    <%= yield %>
    <hr />
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/micro_posts/_form.html.erb
<%= form_for(@micro_post) do |f| %>
  <% if @micro_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micro_post.errors.count, "error") %> prohibited this micro_post from being saved:</h2>

      <ul>
      <% @micro_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/micro_posts/_micro_post.html.erb
<p>
    <span class='micro_post_timestamp'>
        <%= micro_post.created_at.strftime("%m/%d %I-%M") %>
    </span>
    <%= micro_post.content %>
</p>

app/views/micro_posts/edit.html.erb
<h1>Editing micro_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @micro_post %> |
<%= link_to 'Back', micro_posts_path %>

app/views/micro_posts/index.html.erb
<h1>Listing micro_posts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @micro_posts.each do |micro_post| %>
  <tr>
    <td><%= micro_post.user_id %></td>
    <td><%= micro_post.content %></td>
    <td><%= link_to 'Show', micro_post %></td>
    <td><%= link_to 'Edit', edit_micro_post_path(micro_post) %></td>
    <td><%= link_to 'Destroy', micro_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micro post', new_micro_post_path %>

app/views/micro_posts/new.html.erb
<h1>New micro_post</h1>

<%= render 'form' %>

<%= link_to 'Back', micro_posts_path %>

app/views/micro_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @micro_post.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @micro_post.content %>
</p>


<%= link_to 'Edit', edit_micro_post_path(@micro_post) %> |
<%= link_to 'Back', micro_posts_path %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class='row'>
    <div class='span12'>
        <h1>About</h1>
        <p>
          Like Twitter... but better
        </p>
    </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class='row'>
    <div class='span12'>
        <h1>Help</h1>
        <p>
          Get help on the INFO2310 MicroPoster at 
          <a href="http://curails.herokuapp.com">the course website</a>
        </p>
    </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class='hero-unit'>
    <h1>INFO 2310 MicroPoster</h1>
    <p>
      This is a sample website used in INFO 2310 to learn Ruby on Rails.
      Please sign up and share your thoughts with us in 5-140 character chunks.
    </p>

    <% unless signed_in? %>
    <p>
        <%= link_to 'Sign Up', new_user_path, class: 'btn btn-primary btn-large' %>
    </p>
    <% end %>
    
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
    <%= pluralize(@user.micro_posts.length, "MicroPost") %>
</p>

<%= render @user.micro_posts %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>